          ---
- name: Configure Linux Servers
  hosts: c8.local
  become: true
  tasks:
    - name: Disable SELinux
      selinux:
        state: disabled
    - name: Stop and Disable firewalld
      systemd:
        name: firewalld
        state: stopped
        enabled: no
- name: Configure Frontend (Nginx)
  hosts: frontend
  become: true
  tasks:
    - name: Install Nginx
      package:
        name: nginx
        state: present
    - name: Configure Nginx as a Reverse Proxy
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - Restart Nginx
  handlers:
    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted
